version: 1

update_configs:
  - package_manager: "javascript"
    default_labels:
      - "dependencies"
      - "govuk-pay"
      - "javascript"
    directory: "/"
    update_schedule: "weekly"
    allowed_updates:
      - match:
          dependency_type: "development"
          update_type: "security"
      - match:
          dependency_type: "production"
          update_type: "all"
  - package_manager: "docker"
    default_labels:
      - "dependencies"
      - "govuk-pay"
      - "docker"
    directory: "/"
    update_schedule: "weekly"
